/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for Rekord objects
 */
 export type RekorSchema = HashedRekorV001Schema;

 /**
  * Schema for Hashed Rekord object
  */
 export interface HashedRekorV001Schema {
   /**
    * Information about the detached signature associated with the entry
    */
   signature: {
     /**
      * Specifies the content of the signature inline within the document
      */
     content?: string;
     /**
      * The public key that can verify the signature
      */
     publicKey?: {
       /**
        * Specifies the content of the public key inline within the document
        */
       content?: string;
       [k: string]: unknown;
     };
     [k: string]: unknown;
   };
   /**
    * Information about the content associated with the entry
    */
   data: {
     /**
      * Specifies the hash algorithm and value for the content
      */
     hash?: {
       /**
        * The hashing function used to compute the hash value
        */
       algorithm: "sha256";
       /**
        * The hash value for the content
        */
       value: string;
       [k: string]: unknown;
     };
     [k: string]: unknown;
   };
   [k: string]: unknown;
 }